#!/usr/bin/env python3
"""
filter_offsets.py
- Reads external_offsets.h  &  internal_offsets.h
- Removes every '%...' hash line
- Keeps only the offsets that matter for external cheats
- Writes clean_external.h  &  clean_internal.h
"""

import re
from pathlib import Path

# ----------------------------------------------------------------------
# INPUT / OUTPUT
# ----------------------------------------------------------------------
EXT_IN   = Path("external_offsets.h")
INT_IN   = Path("internal_offsets.h")
EXT_OUT  = Path("clean_external.h")
INT_OUT  = Path("clean_internal.h")

if not EXT_IN.is_file() or not INT_IN.is_file():
    print("[ERROR] external_offsets.h or internal_offsets.h not found!")
    exit(1)

# ----------------------------------------------------------------------
# READ RAW FILES
# ----------------------------------------------------------------------
ext_raw = EXT_IN.read_text(encoding="utf-8")
int_raw = INT_IN.read_text(encoding="utf-8")

# ----------------------------------------------------------------------
# REGEX HELPERS
# ----------------------------------------------------------------------
#   roffset <Name> = 0xABCDEF;
OFFSET_RE = re.compile(r'roffset\s+([^\s=]+)\s*=\s*(0x[0-9a-fA-F]+);')

# ----------------------------------------------------------------------
# 1. EXTERNAL – class pointers (static TypeInfo*)
# ----------------------------------------------------------------------
def parse_external(raw: str) -> dict:
    offsets = {}
    for line in raw.splitlines():
        m = OFFSET_RE.search(line)
        if not m:
            continue
        name, addr = m.group(1), m.group(2)
        # skip hash names
        if name.startswith('%'):
            continue
        offsets[name] = addr
    return offsets

ext_dict = parse_external(ext_raw)

# ----- keep only the ones we care about -----
KEEP_EXTERNAL = {
    # Core
    "BaseNetworkable", "BasePlayer", "BaseEntity", "BaseCombatEntity",
    "LocalPlayer", "MainCamera", "ConVar_Graphics",
    # Inventory / weapons
    "PlayerInventory", "BaseProjectile", "Item", "HeldEntity",
    # View / bones
    "PlayerEyes", "PlayerModel", "RecoilProperties",
    # Misc useful
    "GameObject", "Transform", "Camera", "Graphics"
}

clean_ext = {k: v for k, v in ext_dict.items() if any(p in k for p in KEEP_EXTERNAL)}

# ----------------------------------------------------------------------
# 2. INTERNAL – fields & methods
# ----------------------------------------------------------------------
def parse_internal(raw: str) -> dict:
    offsets = {}
    for line in raw.splitlines():
        m = OFFSET_RE.search(line)
        if not m:
            continue
        name, addr = m.group(1), m.group(2)
        # skip hash names
        if name.startswith('%'):
            continue
        offsets[name] = addr
    return offsets

int_dict = parse_internal(int_raw)

# ----- keep only useful fields / methods -----
KEEP_INTERNAL_PREFIXES = (
    "BasePlayer_", "PlayerModel_", "PlayerEyes_", "BaseEntity_",
    "BaseCombatEntity_", "BaseProjectile_", "PlayerInventory_",
    "Item_", "HeldEntity_", "Transform_", "RecoilProperties_",
    "ConVar_Graphics_", "MainCamera_"
)

KEEP_INTERNAL_EXACT = {
    # health
    "BasePlayer__health", "BaseCombatEntity__health",
    # position / transform
    "BaseEntity__position", "BaseEntity_transform",
    # bones
    "PlayerModel_boneTransforms", "PlayerModel_position",
    # view
    "PlayerEyes_viewOffset", "PlayerEyes_bodyRotation",
    # recoil
    "BaseProjectile_recoil", "RecoilProperties_recoilYawMin",
    # inventory
    "PlayerInventory_containerBelt", "PlayerInventory_containerWear",
    # camera / matrix
    "MainCamera_matrix", "ConVar_Graphics_fov"
}

clean_int = {}
for name, addr in int_dict.items():
    if any(name.startswith(p) for p in KEEP_INTERNAL_PREFIXES):
        clean_int[name] = addr
    elif name in KEEP_INTERNAL_EXACT:
        clean_int[name] = addr

# ----------------------------------------------------------------------
# 3. WRITE CLEAN HEADERS
# ----------------------------------------------------------------------
def write_header(path: Path, data: dict, title: str):
    lines = [
        f"// {title}",
        "// Auto-generated by filter_offsets.py – DO NOT EDIT",
        "",
        "#pragma once",
        "#include <cstdint>",
        "#define roffset static uintptr_t",
        "",
        "namespace rust {",
        ""
    ]
    for name in sorted(data.keys()):
        lines.append(f"\troffset {name} = {data[name]};")
    lines += ["", "} // namespace rust", ""]
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[OK] {path.name}  →  {len(data)} offsets")

write_header(EXT_OUT, clean_ext, "CLEAN EXTERNAL OFFSETS – ESP / Aimbot / No-Recoil")
write_header(INT_OUT, clean_int, "CLEAN INTERNAL OFFSETS – Fields & Methods")

# ----------------------------------------------------------------------
# 4. QUICK-LOOK SUMMARY
# ----------------------------------------------------------------------
print("\n=== QUICK-LOOK ===")
if "BaseNetworkable_TypeInfo_c" in clean_ext:
    print(f"BaseNetworkable  →  {clean_ext['BaseNetworkable_TypeInfo_c']}")
if "MainCamera_TypeInfo_c" in clean_ext:
    print(f"MainCamera       →  {clean_ext['MainCamera_TypeInfo_c']}")
if "LocalPlayer_TypeInfo_c" in clean_ext:
    print(f"LocalPlayer      →  {clean_ext['LocalPlayer_TypeInfo_c']}")

print("\nDone! Use the two new files in your cheat project.")